require("plugins");
require("web_devicons");
require("file_explorer");
require("general_keymaps");
require("code_commenter");
require("general_settings");
require("git_plugin");
require("statusline");
require("LSP");
